const SCPT_DRAFTS_2022 = [
    {
        name: "SCPT 2022 Finals",
        slices: "79 35 34 64 78 | 27 29 46 44 25 | 40 37 31 65 41 | 39 66 69 47 74 | 48 76 68 20 19 | 67 28 49 73 26",
        labels: [
            "NekroDiesTwice",
            "NerfZerg",
            "Mantis",
            "Jonno",
            "nerdY2K",
            "codytct",
        ].join("|"),
        clock: 28800,
        factionSets: ["Ul|Winnu|N'orr|Yssaril|Sol|Arborec|Nomad|Mahact"],
    },
    {
        name: "SCPT 2022 Semi-Finals",
        slices: "48,25,70,67,28|23,64,33,78,65|21,40,69,50,38|35,39,34,44,61|41,26,30,77,73|72,79,32,22,66",
        labels: [
            "Rift of the Valkyries",
            "Drunken Sailor",
            "Jeol Ir: The Entertainer",
            "Public Domain Smooth",
            "Mellon Tell Lodorture",
            "In the Hall of the Asteroid King",
        ].join("|"),
        clock: 28800,
        chooseFactionSet: true,
        factionSets: [
            "Saar|Mentak|L1Z1X|Naaz-Rokha|Sol|Xxcha|Winnu",
            "Yssaril|Empyrean|Sol|Yin|Nekro|Letnev|Creuss",
            "Ul|Empyrean|Arborec|L1Z1X|Muaat|Naalu|Vuil'raith",
            "Jol-Nar|N'orr|Argent|Arborec|Mentak|Nekro|Yin",
            "Nomad|Argent|Creuss|Hacan|Naaz-Rokha|Vuil'raith|Xxcha",
            "Mahact|Winnu|Hacan|Letnev|Muaat|Naalu|N'orr",
        ],
    },
    {
        name: "SCPT 2022 Prelim",
        slices: "28,19,25,43,47|34,77,36,41,64|37,60,39,50,67|42,75,78,59,24|76,66,40,62,44|68,73,79,20,65|46,71,63,31,26",
        labels: "Twilight Imperium 4th Edition|The Glass House|Custodian's Gambit|Soft Launch|Grand Opening|Between a Rock and a Slow Place|Winslayer's Dugout",
        clock: 28800,
        factionSets: [
            "Argent|Saar|Mahact|Naaz-Rokha|Nomad|Titans|Vuil'raith",
            "Hacan|Yin|L1Z1X|Letnev|Mentak|Creuss|Xxcha",
            "Arborec|Mentak|Naalu|Nekro|Sardakk|Yin|L1Z1X",
            "Argent|Empyrean|Jol-Nar|Letnev|Naaz-Rokha|Sol|Titans",
            "Creuss|L1Z1X|Mahact|Muaat|Nomad|Winnu|Naalu",
            "Arborec|Hacan|Mentak|Naaz-Rokha|Nekro|Saar|Yssaril",
            "Creuss|Empyrean|Muaat|Sardakk|Sol|Xxcha|Yin",
            "Arborec|Creuss|Mahact|Sardakk|Winnu|Xxcha|Yin",
            "Argent|Empyrean|Muaat|Saar|Sol|Vuil'raith|Yssaril",
            "Winnu|Jol-Nar|L1Z1X|Letnev|Naalu|Nekro|Titans",
            "Arborec|Argent|Jol-Nar|Letnev|Nomad|Vuil'raith|Nekro",
            "Hacan|Mentak|Muaat|Naalu|Xxcha|Winnu|Yssaril",
        ],
    },
    {
        name: "SCPT 2022 Qualifier",
        slices: "39,35,41,66,74|26,30,59,67,49|27,69,78,64,44|43,61,36,40,73|50,37,76,20,68|65,24,46,79,28|42,25,29,47,62",
        labels: "Hope|Golden Corral|Tom Hanks|Live Free or Gash Hard|Mama’s Drama|Antimassachusetts|Chili Dogs on the Beach",
        clock: 28800,
        factionSets: [
            "Argent|Creuss|Empyrean|Mahact|Naaz-Rokha|Nomad|Titans|Vuil'raith",
            "Arborec|Muaat|Naalu|Nekro|Saar|Winnu|Yin|Yssaril",
            "Hacan|Jol-Nar|L1Z1X|Letnev|Mentak|Sardakk|Sol|Xxcha",
            "Creuss|L1Z1X|Mahact|Nomad|Saar|Vuil'raith|Winnu|Xxcha",
            "Arborec|Mentak|Muaat|Naalu|Nekro|Sardakk|Yin|Yssaril",
            "Argent|Empyrean|Hacan|Jol-Nar|Letnev|Naaz-Rokha|Sol|Titans",
            "Creuss|L1Z1X|Mahact|Muaat|Nomad|Sol|Winnu|Xxcha",
            "Arborec|Empyrean|Hacan|Mentak|Naaz-Rokha|Nekro|Saar|Yssaril",
            "Argent|Jol-Nar|Letnev|Naalu|Sardakk|Titans|Vuil'raith|Yin",
            "Creuss|Empyrean|Jol-Nar|Muaat|Sardakk|Nomad|Sol|Xxcha",
            "Argent|Mahact|Naalu|Nekro|Saar|Naaz-Rokha|Winnu|Yssaril",
            "Arborec|Hacan|L1Z1X|Letnev|Mentak|Titans|Vuil'raith|Yin",
            "Arborec|Creuss|Mahact|Mentak|Sardakk|Winnu|Xxcha|Yin",
            "Argent|Empyrean|Muaat|Naaz-Rokha|Saar|Sol|Vuil'raith|Yssaril",
            "Hacan|Jol-Nar|L1Z1X|Letnev|Naalu|Nekro|Nomad|Titans",
            "Arborec|Argent|Jol-Nar|Letnev|Nomad|Sardakk|Vuil'raith|Xxcha",
            "Creuss|Empyrean|L1Z1X|Nekro|Saar|Sol|Titans|Yin",
            "Hacan|Mahact|Mentak|Muaat|Naalu|Naaz-Rokha|Winnu|Yssaril",
        ],
    },
];

module.exports = { SCPT_DRAFTS_2022 };
