const SCPT_DRAFTS = [
    {
        name: "SCPT 2022 Qualifier",
        slices: "39,35,41,66,74|26,30,59,67,49|27,69,78,64,44|43,61,36,40,73|50,37,76,20,68|65,24,46,79,28|42,25,29,47,62",
        labels: "Hope|Golden Corral|Tom Hanks|Live Free or Gash Hard|Mama’s Drama|Antimassachusetts|Chili Dogs on the Beach",
        clock: 28800,
        factionSets: [
            "Argent|Creuss|Empyrean|Mahact|Naaz-Rokha|Nomad|Titans|Vuil'raith",
            "Arborec|Muaat|Naalu|Nekro|Saar|Winnu|Yin|Yssaril",
            "Hacan|Jol-Nar|L1Z1X|Letnev|Mentak|Sardakk|Sol|Xxcha",
            "Creuss|L1Z1X|Mahact|Nomad|Saar|Vuil'raith|Winnu|Xxcha",
            "Arborec|Mentak|Muaat|Naalu|Nekro|Sardakk|Yin|Yssaril",
            "Argent|Empyrean|Hacan|Jol-Nar|Letnev|Naaz-Rokha|Sol|Titans",
            "Creuss|L1Z1X|Mahact|Muaat|Nomad|Sol|Winnu|Xxcha",
            "Arborec|Empyrean|Hacan|Mentak|Naaz-Rokha|Nekro|Saar|Yssaril",
            "Argent|Jol-Nar|Letnev|Naalu|Sardakk|Titans|Vuil'raith|Yin",
            "Creuss|Empyrean|Jol-Nar|Muaat|Sardakk|Nomad|Sol|Xxcha",
            "Argent|Mahact|Naalu|Nekro|Saar|Naaz-Rokha|Winnu|Yssaril",
            "Arborec|Hacan|L1Z1X|Letnev|Mentak|Titans|Vuil'raith|Yin",
            "Arborec|Creuss|Mahact|Mentak|Sardakk|Winnu|Xxcha|Yin",
            "Argent|Empyrean|Muaat|Naaz-Rokha|Saar|Sol|Vuil'raith|Yssaril",
            "Hacan|Jol-Nar|L1Z1X|Letnev|Naalu|Nekro|Nomad|Titans",
            "Arborec|Argent|Jol-Nar|Letnev|Nomad|Sardakk|Vuil'raith|Xxcha",
            "Creuss|Empyrean|L1Z1X|Nekro|Saar|Sol|Titans|Yin",
            "Hacan|Mahact|Mentak|Muaat|Naalu|Naaz-Rokha|Winnu|Yssaril",
        ],
    },
    {
        name: "SCPT 2022 Prelim",
        slices: "28,19,25,43,47|34,77,36,41,64|37,60,39,50,67|42,75,78,59,24|76,66,40,62,44|68,73,79,20,65|46,71,63,31,26",
        labels: "Twilight Imperium 4th Edition|The Glass House|Custodian's Gambit|Soft Launch|Grand Opening|Between a Rock and a Slow Place|Winslayer's Dugout",
        clock: 28800,
        factionSets: [
            "Argent|Saar|Mahact|Naaz-Rokha|Nomad|Titans|Vuil'raith",
            "Hacan|Yin|L1Z1X|Letnev|Mentak|Creuss|Xxcha",
            "Arborec|Mentak|Naalu|Nekro|Sardakk|Yin|L1Z1X",
            "Argent|Empyrean|Jol-Nar|Letnev|Naaz-Rokha|Sol|Titans",
            "Creuss|L1Z1X|Mahact|Muaat|Nomad|Winnu|Naalu",
            "Arborec|Hacan|Mentak|Naaz-Rokha|Nekro|Saar|Yssaril",
            "Creuss|Empyrean|Muaat|Sardakk|Sol|Xxcha|Yin",
            "Arborec|Creuss|Mahact|Sardakk|Winnu|Xxcha|Yin",
            "Argent|Empyrean|Muaat|Saar|Sol|Vuil'raith|Yssaril",
            "Winnu|Jol-Nar|L1Z1X|Letnev|Naalu|Nekro|Titans",
            "Arborec|Argent|Jol-Nar|Letnev|Nomad|Vuil'raith|Nekro",
            "Hacan|Mentak|Muaat|Naalu|Xxcha|Winnu|Yssaril",
        ],
    },
];

const FACTION_NAME_TO_NSID_NAME = {
    Arborec: "arborec",
    Argent: "argent",
    Creuss: "creuss",
    Empyrean: "empyrean",
    Hacan: "hacan",
    "Jol-Nar": "jolnar",
    L1Z1X: "l1z1x",
    Letnev: "letnev",
    Mahact: "mahact",
    Mentak: "mentak",
    Muaat: "muaat",
    "N'orr": "norr",
    Naalu: "naalu",
    "Naaz-Rokha": "naazrokha",
    Nekro: "nekro",
    Nomad: "nomad",
    Saar: "saar",
    Sol: "sol",
    Ul: "ul",
    "Vuil'raith": "vuilraith",
    Winnu: "winnu",
    Xxcha: "xxcha",
    Yin: "yin",
    Yssaril: "yssaril",

    Sardakk: "norr",
    Titans: "ul",
};

module.exports = { SCPT_DRAFTS, FACTION_NAME_TO_NSID_NAME };
