const SCPT_DRAFTS_2025 = [
    {
        name: "Qualifier",
        enabled: true,
        slices: [
            "27,73,47,44,26", //
            "30,39,76,80,65",
            "42,64,75,72,49",
            "79,37,50,71,66",
            "34,41,70,78,25",
            "40,20,36,45,74",
        ].join("|"),
        labels: [
            "Will, again", //
            "Rigely field (Where the girls go out)",
            "Devil went back down to Velnor (He forgot something)",
            "Yellow slice because it has Hope's End",
            "Gravity's DOOT DOOT",
            "Viva Las Lorxembourg",
        ].join("|"),
        factionCount: 6,
        resizeToPlayerCount: true,
        clock: 28800,
    },
    {
        name: "Prelims",
        enabled: true,
        slices: "",
        labels: ["", "", "", "", "", ""].join("|"),
        factionCount: 6,
        clock: 28800,
        resizeToPlayerCount: true,
        grabFromHistory: true,
    },
    {
        name: "Semi-finals",
        enabled: true,
        slices: "",
        labels: ["", "", "", "", "", ""].join("|"),
        factionCount: 6,
        // no clock for semis

        semis1: {
            name: "Semi-finals 1",
            factions: "Naalu|Hacan|Nekro|Jol-Nar|Letnev|L1Z1X",
            slices: [
                "40,37,33,21,44",
                "42,50,30,26,36",
                "48,31,29,22,45",
                "39,46,35,24,34",
                "49,38,32,25,41",
                "43,47,28,19,27",
            ].join("|"),
            labels: [
                "Vaunt",
                "Mage",
                "9 of Spades",
                "Schroeder",
                "Magi",
                "Jaynor",
            ].join("|"),
            factionCount: 6,
        },
        semis2: {
            name: "Semi-finals ",
            factions: "yin|hacan|l1z1x|mentak|creuss|xxcha",
            slices: [
                "28,30,19,42,48",
                "22,33,37,26,46",
                "36,27,24,40,45",
                "29,31,20,41,48",
                "21,35,32,39,50",
                "34,38,23,25,44",
            ].join("|"),
            labels: [
                "Moose",
                "Brian",
                "Ginger",
                "John",
                "Duke LukeM",
                "Shorty55",
            ].join("|"),
            factionCount: 6,
        },
        semis3: {
            name: "Semi-finals 3",
            factions: "muaat|argent|empyrean|vuilraith|naazrokha|saar",
            slices: [
                "21,69,68,39,47",
                "29,74,46,64,67",
                "27,37,45,26,78",
                "73,28,43,40,60",
                "19,76,41,79,65",
                "50,70,72,25,20",
            ].join("|"),
            labels: [
                "Ondra",
                "Wolphin",
                "The Humble Checkmate",
                "teddysjamforyou",
                "HG Kool aid",
                "telagos",
            ].join("|"),
            factionCount: 6,
        },
        semis4: {
            name: "Semi-finals 4",
            factions: "ul|nomad|norr|yssaril|sol|mahact",
            slices: [
                "67,28,50,73,26",
                "27,29,46,45,25",
                "40,37,31,65,41",
                "77,76,68,20,19",
                "79,35,34,64,78",
                "39,66,69,47,74",
            ].join("|"),
            labels: [
                "codytct",
                "NerfZerg",
                "mantis",
                "nerdY2K",
                "NekroDiesTwice",
                "Jonno",
            ].join("|"),
            factionCount: 6,
        },
        semis5: {
            name: "Semi-finals 5",
            factions: "mahact|creuss|yssaril|empyrean|l1z1x|hacan",
            slices: [
                "73,39,24,80,71",
                "49,79,30,62,76",
                "50,22,59,67,65",
                "47,64,74,37,41",
                "42,26,72,35,77",
                "61,40,70,68,36",
            ].join("|"),
            labels: [
                "jadiimjedi",
                "Sir Craigsworth",
                "Deshuga",
                "aljce",
                "dzhiriki",
                "Arratain",
            ].join("|"),
            factionCount: 6,
        },
        semis6: {
            name: "Semi-finals 6",
            factions: "mentak|yin|keleres_argent|norr|muaat|arborec",
            slices: [
                "35,25,44,73,49",
                "34,22,67,47,66",
                "27,40,72,79,65",
                "41,32,48,59,69",
                "78,75,42,24,26",
                "39,76,62,80,64",
            ].join("|"),
            labels: [
                "Walrus Berzerker",
                "The Meta",
                "GreenFlame",
                "catoftheyear",
                "dzhiriki",
                "Fingolfin",
            ].join("|"),
            factionCount: 6,
        },
    },
    {
        name: "Finals",
        enabled: true,
        slices: [
            "64,22,45,75,70",
            "74,68,40,60,21",
            "62,39,67,72,38",
            "42,27,34,26,50",
            "41,30,29,80,63",
            "31,25,79,76,78",
        ].join("|"),
        labels: [
            "Circlet of the Void",
            "Salient Sun",
            "Barren Husk",
            "Forlorn Shadow",
            "Neuraloop",
            "Appollo Protocol",
        ].join("|"),
        factions: [
            "sol",
            "xxcha",
            "jolnar",
            "keleres_mentak",
            "creuss",
            "naalu",
        ].join("|"),
        factionCount: 6,
        outerSystems: true,
    },
];

module.exports = { SCPT_DRAFTS_2025 };
