const FACTION_DATA = [
    {
        abilities: ["mitosis"],
        commodities: 3,
        faction: "arborec",
        home: 5,
        leaders: {
            agents: ["letani_ospha"],
            commanders: ["dirzuga_rophal"],
            heroes: ["letani_miasmiala"],
        },
        promissoryNotes: ["stymie"],
        source: "base",
        startingTech: ["magen_defense_grid"],
        startingUnits: {
            carrier: 1,
            cruiser: 1,
            fighter: 2,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: ["bioplasmosis"],
        units: [
            "duha_menaimon",
            "letani_warrior",
            "letani_warrior_2",
            "letani_behemoth",
        ],
    },
    {
        abilities: ["munitions_reserves", "armada"],
        commodities: 2,
        faction: "letnev",
        home: 10,
        leaders: {
            agents: ["viscount_unlenn"],
            commanders: ["rear_admiral_farran"],
            heroes: ["darktalon_treilla"],
        },
        promissoryNotes: ["war_funding"],
        source: "base",
        startingTech: ["antimass_deflectors", "plasma_scoring"],
        startingUnits: {
            carrier: 1,
            destroyer: 1,
            dreadnought: 1,
            fighter: 1,
            infantry: 3,
            spacedock: 1,
        },
        techs: ["l4_disruptors", "noneuclidean_shielding"],
        units: ["arc_secundus", "dunlain_reaper"],
    },
    {
        abilities: ["scavenge", "nomadic"],
        commodities: 3,
        faction: "saar",
        home: 11,
        leaders: {
            agents: ["captain_mendosa"],
            commanders: ["rowl_sarrig"],
            heroes: ["gurno_aggero"],
        },
        promissoryNotes: ["raghs_call"],
        source: "base",
        startingTech: ["antimass_deflectors"],
        startingUnits: {
            carrier: 2,
            cruiser: 1,
            fighter: 2,
            infantry: 4,
            spacedock: 1,
        },
        techs: ["chaos_mapping"],
        units: [
            "son_of_ragh",
            "floating_factory",
            "floating_factory_2",
            "scavenger_zeta",
        ],
    },
    {
        abilities: ["star_forge", "gashlai_physiology"],
        commodities: 4,
        faction: "muaat",
        home: 4,
        leaders: {
            agents: ["umbat"],
            commanders: ["magmus"],
            heroes: ["adjudicator_baal"],
        },
        promissoryNotes: ["fires_of_the_gashlai"],
        source: "base",
        startingTech: ["plasma_scoring"],
        startingUnits: {
            fighter: 2,
            infantry: 4,
            spacedock: 1,
            warsun: 1,
        },
        techs: ["magmus_reactor"],
        units: [
            "the_inferno",
            "prototype_war_sun",
            "prototype_war_sun_2",
            "ember_colossus",
        ],
    },
    {
        abilities: ["masters_of_trade", "guild_ships", "arbiters"],
        commodities: 6,
        faction: "hacan",
        home: 16,
        leaders: {
            agents: ["carth_of_golden_sands"],
            commanders: ["gila_the_silvertongue"],
            heroes: ["harrugh_gefhara"],
        },
        promissoryNotes: ["trade_convoys"],
        source: "base",
        startingTech: ["antimass_deflectors", "sarween_tools"],
        startingUnits: {
            carrier: 2,
            cruiser: 1,
            fighter: 2,
            infantry: 4,
            spacedock: 1,
        },
        techs: ["quantum_datahub_node", "production_biomes"],
        units: ["wrath_of_kenara", "pride_of_kenara"],
    },
    {
        abilities: ["orbital_drop", "versatile"],
        commodities: 4,
        faction: "sol",
        home: 1,
        leaders: {
            agents: ["evelyn_delouis"],
            commanders: ["claire_gibson"],
            heroes: ["jace_x_4th_air_legion"],
        },
        promissoryNotes: ["military_support"],
        source: "base",
        startingTech: ["antimass_deflectors", "neural_motivator"],
        startingUnits: {
            carrier: 2,
            destroyer: 1,
            fighter: 3,
            infantry: 5,
            spacedock: 1,
        },
        techs: [],
        units: [
            "genesis",
            "advanced_carrier",
            "advanced_carrier_2",
            "spec_ops",
            "spec_ops_2",
            "zs_thunderbolt_m2",
        ],
    },
    {
        abilities: ["quantum_entanglement", "slipstream", "creuss_gate"],
        commodities: 4,
        faction: "creuss",
        home: 51,
        leaders: {
            agents: ["emissary_taivra"],
            commanders: ["sai_seravus"],
            heroes: ["riftwalker_meian"],
        },
        promissoryNotes: ["creuss_iff"],
        source: "base",
        startingTech: ["gravity_drive"],
        startingUnits: {
            carrier: 1,
            destroyer: 2,
            fighter: 2,
            infantry: 4,
            spacedock: 1,
        },
        techs: ["wormhole_generator", "dimensional_splicer"],
        units: ["hil_colish", "icarus_drive"],
    },
    {
        abilities: ["assimilate", "harrow"],
        commodities: 2,
        faction: "l1z1x",
        home: 6,
        leaders: {
            agents: ["i48s"],
            commanders: ["2ram"],
            heroes: ["the_helmsman"],
        },
        promissoryNotes: ["cybernetic_enhancements"],
        source: "base",
        startingTech: ["neural_motivator", "plasma_scoring"],
        startingUnits: {
            carrier: 1,
            dreadnought: 1,
            fighter: 3,
            infantry: 5,
            pds: 1,
            spacedock: 1,
        },
        techs: ["inheritance_systems"],
        units: ["001", "superdreadnought", "superdreadnought_2", "annihilator"],
    },
    {
        abilities: ["ambush", "pillage"],
        commodities: 2,
        faction: "mentak",
        home: 2,
        leaders: {
            agents: ["suffi_an"],
            commanders: ["sula_mentarion"],
            heroes: ["ipswitch_loose_cannon"],
        },
        promissoryNotes: ["promise_of_protection"],
        source: "base",
        startingTech: ["sarween_tools", "plasma_scoring"],
        startingUnits: {
            carrier: 1,
            cruiser: 2,
            fighter: 3,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: ["mirror_computing", "salvage_operations"],
        units: ["fourth_moon", "moll_terminus"],
    },
    {
        abilities: ["telepathic", "foresight"],
        commodities: 3,
        faction: "naalu",
        home: 9,
        leaders: {
            agents: ["zeu"],
            commanders: ["maban"],
            heroes: ["the_oracle"],
        },
        promissoryNotes: ["gift_of_prescience"],
        source: "base",
        startingTech: ["neural_motivator", "sarween_tools"],
        startingUnits: {
            carrier: 1,
            cruiser: 1,
            destroyer: 1,
            fighter: 3,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: ["neuroglaive"],
        units: [
            "matriarch",
            "hybrid_crystal_fighter",
            "hybrid_crystal_fighter_2",
            "iconoclast",
        ],
    },
    {
        abilities: [
            "galactic_threat",
            "technological_singularity",
            "propagation",
        ],
        commodities: 3,
        faction: "nekro",
        home: 8,
        leaders: {
            agents: ["nekro_malleon"],
            commanders: ["nekro_acidos"],
            heroes: ["unitdsgnflayesh"],
        },
        promissoryNotes: ["antivirus"],
        source: "base",
        startingTech: [
            "dacxive_animators",
            "valefar_assimilator_x",
            "valefar_assimilator_y",
        ],
        startingUnits: {
            carrier: 1,
            cruiser: 1,
            dreadnought: 1,
            fighter: 2,
            infantry: 2,
            spacedock: 1,
        },
        techs: ["valefar_assimilator_x", "valefar_assimilator_y"],
        units: ["the_alastor", "mordred"],
    },
    {
        abilities: ["unrelenting"],
        commodities: 3,
        faction: "norr",
        home: 13,
        leaders: {
            agents: ["tro"],
            commanders: ["ghom_sekkus"],
            heroes: ["shval_harbinger"],
        },
        promissoryNotes: ["tekklar_legion"],
        source: "base",
        startingTech: [],
        startingUnits: {
            carrier: 2,
            cruiser: 1,
            infantry: 5,
            pds: 1,
            spacedock: 1,
        },
        techs: ["valkyrie_particle_weave"],
        units: [
            "cmorran_norr",
            "exotrireme",
            "exotrireme_2",
            "valkyrie_exoskeleton",
        ],
    },
    {
        abilities: ["fragile", "brilliant", "analytical"],
        commodities: 4,
        faction: "jolnar",
        home: 12,
        leaders: {
            agents: ["doctor_sucaban"],
            commanders: ["ta_zern"],
            heroes: ["rin_the_masters_legacy"],
        },
        promissoryNotes: ["research_agreement"],
        source: "base",
        startingTech: [
            "antimass_deflectors",
            "neural_motivator",
            "sarween_tools",
            "plasma_scoring",
        ],
        startingUnits: {
            carrier: 2,
            dreadnought: 1,
            fighter: 1,
            infantry: 2,
            pds: 2,
            spacedock: 1,
        },
        techs: ["spacial_conduit_cylinder", "eres_siphons"],
        units: ["jns_hylarim", "shield_paling"],
    },
    {
        abilities: ["blood_ties", "reclamation"],
        commodities: 3,
        faction: "winnu",
        home: 7,
        leaders: {
            agents: ["berekar_berekon"],
            commanders: ["rickar_rickani"],
            heroes: ["mathis_mathinus"],
        },
        promissoryNotes: ["acquiescence"],
        source: "base",
        startingTech: [],
        startingUnits: {
            carrier: 1,
            cruiser: 1,
            fighter: 2,
            infantry: 2,
            pds: 1,
            spacedock: 1,
        },
        techs: ["lazax_gate_folding", "hegemonic_trade_policy"],
        units: ["salai_sai_corian", "reclaimer"],
    },
    {
        abilities: ["peace_accords", "quash"],
        commodities: 4,
        faction: "xxcha",
        home: 14,
        leaders: {
            agents: ["ggrocuto_rinn"],
            commanders: ["elder_qanoj"],
            heroes: ["xxekir_grom"],
        },
        promissoryNotes: ["political_favor"],
        source: "base",
        startingTech: ["graviton_laser_system"],
        startingUnits: {
            carrier: 1,
            cruiser: 2,
            fighter: 3,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: ["instinct_training", "nullification_field"],
        units: ["loncara_ssodu", "indomitus"],
    },
    {
        abilities: ["indoctrination", "devotion"],
        commodities: 2,
        faction: "yin",
        home: 3,
        leaders: {
            agents: ["brother_milor"],
            commanders: ["brother_omar"],
            heroes: ["dannel_of_the_tenth"],
        },
        promissoryNotes: ["greyfire_mutagen"],
        source: "base",
        startingTech: ["sarween_tools"],
        startingUnits: {
            carrier: 2,
            destroyer: 1,
            fighter: 4,
            infantry: 4,
            spacedock: 1,
        },
        techs: ["yin_spinner", "impulse_core"],
        units: ["van_hauge", "moyins_ashes"],
    },
    {
        abilities: ["stall_tactics", "scheming", "crafty"],
        commodities: 3,
        faction: "yssaril",
        home: 15,
        leaders: {
            agents: ["ssruu"],
            commanders: ["so_ata"],
            heroes: ["kyver_blade_and_key"],
        },
        promissoryNotes: ["spy_net"],
        source: "base",
        startingTech: ["neural_motivator"],
        startingUnits: {
            carrier: 2,
            cruiser: 1,
            fighter: 2,
            infantry: 5,
            pds: 1,
            spacedock: 1,
        },
        techs: ["mageon_implants", "transparasteel_plating"],
        units: ["ysia_yssrila", "blackshade_infiltrator"],
    },
    {
        abilities: ["the_company", "future_sight"],
        commodities: 4,
        faction: "nomad",
        home: 53,
        leaders: {
            agents: ["the_thundarian"],
            commanders: ["navarch_feng"],
            heroes: ["ahksyl_siven"],
        },
        promissoryNotes: ["the_cavalry"],
        source: "pok",
        startingTech: ["sling_relay"],
        startingUnits: {
            carrier: 1,
            destroyer: 1,
            fighter: 3,
            flagship: 1,
            infantry: 4,
            spacedock: 1,
        },
        techs: ["temporal_command_suite"],
        units: ["memoria", "memoria_2", "quantum_manipulator"],
    },
    {
        abilities: ["devour", "amalgamation", "riftmeld"],
        commodities: 2,
        faction: "vuilraith",
        home: 54,
        leaders: {
            agents: ["the_stillness_of_stars"],
            commanders: ["that_which_molds_flesh"],
            heroes: ["it_feeds_on_carrion"],
        },
        promissoryNotes: ["crucible"],
        source: "pok",
        startingTech: ["self_assembly_routines"],
        startingUnits: {
            carrier: 1,
            cruiser: 1,
            dreadnought: 1,
            fighter: 3,
            infantry: 3,
            spacedock: 1,
        },
        techs: ["vortex"],
        units: [
            "the_terror_between",
            "dimensional_tear",
            "dimensional_tear_2",
            "reanimator",
        ],
    },
    {
        abilities: ["zeal", "raid_formation"],
        commodities: 3,
        faction: "argent",
        home: 58,
        leaders: {
            agents: ["trilossa_aun_mirik"],
            commanders: ["trrakan_aun_zulok"],
            heroes: ["mirik_aun_sissiri"],
        },
        promissoryNotes: ["strike_wing_ambuscade"],
        source: "pok",
        startingTech: ["sarween_tools", "neural_motivator", "plasma_scoring"],
        startingUnits: {
            carrier: 1,
            destroyer: 2,
            fighter: 2,
            infantry: 5,
            pds: 1,
            spacedock: 1,
        },
        techs: ["aerie_hololattice"],
        units: [
            "quetzecoatl",
            "strike_wing_alpha",
            "strike_wing_alpha_2",
            "aerie_sentinel",
        ],
    },
    {
        abilities: ["terragenesis", "awaken", "coalescence"],
        commodities: 2,
        faction: "ul",
        home: 55,
        leaders: {
            agents: ["tellurian"],
            commanders: ["tungstantus"],
            heroes: ["ul_the_progenitor"],
        },
        promissoryNotes: ["terraform"],
        source: "pok",
        startingTech: ["antimass_deflectors", "scanlink_drone_network"],
        startingUnits: {
            cruiser: 2,
            dreadnought: 1,
            fighter: 2,
            infantry: 3,
            spacedock: 1,
        },
        techs: [],
        units: [
            "ouranos",
            "saturn_engine",
            "saturn_engine_2",
            "heltitan",
            "heltitan_2",
            "hecatoncheires",
        ],
    },
    {
        abilities: ["voidborn", "aetherpassage", "dark_whispers"],
        commodities: 4,
        faction: "empyrean",
        home: 56,
        leaders: {
            agents: ["acamar"],
            commanders: ["xuange"],
            heroes: ["conservator_procyon"],
        },
        promissoryNotes: ["blood_pact", "dark_pact"],
        source: "pok",
        startingTech: ["dark_energy_tap"],
        startingUnits: {
            carrier: 2,
            destroyer: 1,
            fighter: 2,
            infantry: 4,
            spacedock: 1,
        },
        techs: ["aetherstream", "voidwatch"],
        units: ["dynamo", "watcher"],
    },
    {
        abilities: ["edict", "imperia", "hubris"],
        commodities: 3,
        faction: "mahact",
        home: 52,
        leaders: {
            agents: ["jae_mir_kan"],
            commanders: ["il_na_viroset"],
            heroes: ["airo_shir_aur"],
        },
        promissoryNotes: ["scepter_of_dominion"],
        source: "pok",
        startingTech: ["predictive_intelligence", "biostims"],
        startingUnits: {
            carrier: 1,
            cruiser: 1,
            dreadnought: 1,
            fighter: 2,
            infantry: 3,
            spacedock: 1,
        },
        techs: ["genetic_recombination"],
        units: [
            "arvicon_rex",
            "crimson_legionnaire",
            "crimson_legionnaire_2",
            "starlancer",
        ],
    },
    {
        abilities: ["distant_suns", "fabrication"],
        commodities: 3,
        faction: "naazrokha",
        home: 57,
        leaders: {
            agents: ["garv_and_gunn"],
            commanders: ["dart_and_tai"],
            heroes: ["hesh_and_prit"],
        },
        promissoryNotes: ["black_market_forgery"],
        source: "pok",
        startingTech: ["psychoarchaeology", "ai_development_algorithm"],
        startingUnits: {
            carrier: 2,
            destroyer: 1,
            fighter: 2,
            infantry: 3,
            mech: 1,
            spacedock: 1,
        },
        techs: ["supercharge", "prefab_arcologies"],
        units: ["visz_el_vir", "eidolon"],
    },
];

module.exports = { FACTION_DATA };
