// Incomplete Discordant Stars factions, exported from another platform.
module.exports = [
    {
        abilities: [
            "corporate_entity",
            "holding_company",
            "targeted_acquisition",
        ],
        commodities: 4,
        faction: "veldyr",
        home: 3201,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["vera_khage"],
            heroes: ["auberon_elyrin"],
        },
        promissoryNotes: [
            "branch_office_tax_haven",
            "branch_office_broadcast_hub",
            "branch_office_reserve_bank",
            "branch_office_orbital_shipyard",
        ],
        source: "discordant_stars",
        startingTech: ["dark_energy_tap", "ai_development_algorithm"],
        startingUnits: {
            carrier: 1,
            destroyer: 1,
            dreadnought: 1,
            fighter: 2,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: [],
        units: [
            "richtyrian",
            "lancer_dreadnought",
            "lancer_dreadnought_2",
            "aurora_stormcaller",
        ],
    },
    {
        abilities: ["rally_to_the_cause", "diplomats", "free_people"],
        commodities: 4,
        faction: "free_systems",
        home: 3202,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["president_cyhn"],
            heroes: ["count_otto_pmay"],
        },
        promissoryNotes: ["broadcast_team", "broadcast_teams"],
        source: "discordant_stars",
        startingTech: ["psychoarchaeology"],
        startingUnits: {
            carrier: 1,
            cruiser: 2,
            fighter: 2,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: [],
        units: ["vox", "liberator"],
    },
    {
        abilities: ["cunning", "subterfuge"],
        commodities: 3,
        faction: "lizho",
        home: 3203,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["dume_tathu"],
            heroes: ["khazrin_lizho"],
        },
        promissoryNotes: ["trusted_counselor"],
        source: "discordant_stars",
        startingTech: ["psychoarchaeology", "antimass_deflectors"],
        startingUnits: {
            carrier: 2,
            destroyer: 1,
            fighter: 3,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: [],
        units: [
            "silence_of_stars",
            "heavy_bomber",
            "heavy_bomber_2",
            "orozhin_elite",
        ],
    },
    {
        abilities: ["lithoids", "garden_worlds", "meteor_slings"],
        commodities: 2,
        faction: "khrask",
        home: 3204,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["hkot_tokal"],
            heroes: ["vehl_tikar"],
        },
        promissoryNotes: ["stone_speakers"],
        source: "discordant_stars",
        startingTech: ["scanlink_drone_network", "plasma_scoring"],
        startingUnits: {
            cruiser: 3,
            fighter: 1,
            infantry: 3,
            pds: 1,
            spacedock: 1,
        },
        techs: [],
        units: [
            "splintering_gale",
            "shattered_sky",
            "shattered_sky_2",
            "megalith",
        ],
    },
    {
        abilities: ["the_lady_the_lord", "rule_of_two"],
        commodities: 2,
        faction: "ghemina",
        home: 3205,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["jarl_vel_jarl_jotrun"],
            heroes: [],
        },
        promissoryNotes: ["raid_leaders"],
        source: "discordant_stars",
        startingTech: ["psychoarchaeology", "dark_energy_tap"],
        startingUnits: {
            carrier: 2,
            fighter: 4,
            infantry: 4,
            spacedock: 2,
        },
        techs: [],
        units: [
            "the_lady_the_lord",
            "combat_transport",
            "combat_transport_2",
            "jotun",
        ],
    },
    {
        abilities: ["fine_print", "collateralized_loans", "binding_debts"],
        commodities: 3,
        faction: "vaden",
        home: 3206,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["komdar_borodin"],
            heroes: ["putriv_sirvonsk"],
        },
        promissoryNotes: ["vaden_handshake"],
        source: "discordant_stars",
        startingTech: [
            "neural_motivator",
            "antimass_deflectors",
            "sarween_tools",
        ],
        startingUnits: {
            carrier: 1,
            cruiser: 1,
            dreadnought: 1,
            fighter: 2,
            infantry: 3,
            spacedock: 1,
        },
        techs: [],
        units: ["aurum_vadra", "collector"],
    },
    {
        abilities: ["facsimile", "illusory_presence"],
        commodities: 3,
        faction: "mortheus",
        home: 3207,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["komat"],
            heroes: ["bayan"],
        },
        promissoryNotes: ["secrets_of_the_weave"],
        source: "discordant_stars",
        startingTech: ["dark_energy_tap", "sarween_tools"],
        startingUnits: {
            carrier: 1,
            destroyer: 1,
            dreadnought: 1,
            fighter: 2,
            infantry: 3,
            spacedock: 1,
        },
        techs: [],
        units: ["particle_sieve", "duuban"],
    },
    {
        abilities: ["oracle_ai", "limited_vision", "probability_algorithms"],
        commodities: 3,
        faction: "ilyxum",
        home: 3208,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["lachis"],
            heroes: ["atropha"],
        },
        promissoryNotes: ["read_the_fates"],
        source: "discordant_stars",
        startingTech: ["scanlink_drone_network", "ai_development_algorithm"],
        startingUnits: {
            carrier: 1,
            destroyer: 2,
            fighter: 2,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: [],
        units: ["nemsys", "iledrith"],
    },
    {
        abilities: ["military_industrial_complex", "arms_dealers"],
        commodities: 5,
        faction: "axis",
        home: 3209,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["designer_tckvsk"],
            heroes: ["demiqueen_mdckssk"],
        },
        promissoryNotes: ["industry_secrets"],
        source: "discordant_stars",
        startingTech: ["sarween_tools", "ai_development_algorithm"],
        startingUnits: {
            carrier: 1,
            destroyer: 1,
            dreadnought: 1,
            fighter: 2,
            infantry: 3,
            spacedock: 1,
        },
        techs: [],
        units: ["bearer_of_heavens", "forgetender"],
    },
    {
        abilities: ["policies"],
        commodities: 3,
        faction: "olradin",
        home: 3210,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["knak_halfear"],
            heroes: ["pahn_silverfur"],
        },
        promissoryNotes: ["incite_rebellion", "incite_revolution"],
        source: "discordant_stars",
        startingTech: ["psychoarchaeology", "scanlink_drone_network"],
        startingUnits: {
            carrier: 2,
            cruiser: 1,
            fighter: 3,
            infantry: 4,
            spacedock: 1,
        },
        techs: [],
        units: ["rallypoint", "exemplar"],
    },
    {
        abilities: ["prescient_memories", "divination", "necrophage"],
        commodities: 1,
        faction: "mori",
        home: 3211,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["amanita_muscaria"],
            heroes: ["coprinus_comatus"],
        },
        promissoryNotes: ["gift_of_insight"],
        source: "discordant_stars",
        startingTech: ["predictive_intelligence"],
        startingUnits: {
            carrier: 2,
            cruiser: 1,
            fighter: 1,
            infantry: 6,
            spacedock: 1,
        },
        techs: [],
        units: [
            "psyclobea_qarnyx",
            "amandia_pholdis",
            "mycelium_ring",
            "mycelium_ring_2",
        ],
    },
    {
        abilities: [
            "plausible_deniability",
            "information_brokers",
            "stealth_insertion",
        ],
        commodities: 2,
        faction: "tnelis",
        home: 3212,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["fillipo_rois"],
            heroes: ["turra_sveyar"],
        },
        promissoryNotes: ["plots_within_plots"],
        source: "discordant_stars",
        startingTech: [
            "neural_motivator",
            "antimass_deflectors",
            "plasma_scoring",
        ],
        startingUnits: {
            carrier: 1,
            destroyer: 2,
            fighter: 2,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: [],
        units: ["principia_aneris", "blockade_runner", "daedalon"],
    },
    {
        abilities: ["autonetic_memory", "cybernetic_madness"],
        commodities: 3,
        faction: "cymiae",
        home: 3213,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["koryl_ferax"],
            heroes: ["the_voice_united"],
        },
        promissoryNotes: ["algorithmic_replication"],
        source: "discordant_stars",
        startingTech: ["neural_motivator", "ai_development_algorithm"],
        startingUnits: {
            carrier: 1,
            destroyer: 1,
            dreadnought: 1,
            fighter: 2,
            infantry: 3,
            spacedock: 1,
        },
        techs: [],
        units: [
            "reprocessor_alpha",
            "unholy_abomination",
            "unholy_abomination_2",
            "revenant",
        ],
    },
    {
        abilities: ["industrious", "recycled_materials", "orbital_foundries"],
        commodities: 4,
        faction: "rohdhna",
        home: 3214,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["bunit_205643a"],
            heroes: ["rohvhin_dhna_mk4"],
        },
        promissoryNotes: ["automatons"],
        source: "discordant_stars",
        startingTech: ["psychoarchaeology", "sarween_tools"],
        startingUnits: {
            carrier: 2,
            destroyer: 1,
            fighter: 3,
            infantry: 3,
            spacedock: 1,
        },
        techs: [],
        units: ["kyvir", "terrafactory", "terrafactory_2", "autofabricator"],
    },
    {
        abilities: ["obsessive_designs", "biophobic", "paranoia"],
        commodities: 2,
        faction: "zelian",
        home: 3215,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["zelian_b"],
            heroes: ["zelian_r"],
        },
        promissoryNotes: ["hyperkinetic_ordinance"],
        source: "discordant_stars",
        startingTech: ["antimass_deflectors", "ai_development_algorithm"],
        startingUnits: {
            carrier: 1,
            destroyer: 1,
            dreadnought: 1,
            fighter: 1,
            infantry: 5,
            pds: 1,
            spacedock: 1,
        },
        techs: [],
        units: ["worldcracker", "impactor", "impactor_2", "collider"],
    },
    {
        abilities: ["cargo_raiders", "scour", "raze"],
        commodities: 2,
        faction: "vaylerian",
        home: 3216,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["pyndil_gonsuul"],
            heroes: ["dyln_harthuul"],
        },
        promissoryNotes: ["clans_favor"],
        source: "discordant_stars",
        startingTech: ["neural_motivator", "dark_energy_tap"],
        startingUnits: {
            carrier: 1,
            cruiser: 1,
            destroyer: 1,
            fighter: 3,
            infantry: 3,
            pds: 1,
            spacedock: 1,
        },
        techs: [],
        units: ["lost_cause", "raider", "raider_2", "eclipse"],
    },
    {
        abilities: ["mercenaries", "data_leak", "black_markets"],
        commodities: 4,
        faction: "florzen",
        home: 3217,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["quaxdol_junitas"],
            heroes: ["banua_gowen"],
        },
        promissoryNotes: ["underground_market"],
        source: "discordant_stars",
        startingTech: ["neural_motivator", "scanlink_drone_network"],
        startingUnits: {
            carrier: 2,
            fighter: 4,
            infantry: 4,
            spacedock: 1,
        },
        techs: [],
        units: ["man_o_war", "corsair", "corsair_2", "privateer"],
    },
    {
        abilities: ["capital_fleet", "migrant_fleet", "flotilla"],
        commodities: 2,
        faction: "dihmohn",
        home: 3218,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["clona_bathru"],
            heroes: ["verrisus_ypru"],
        },
        promissoryNotes: ["combat_drills"],
        source: "discordant_stars",
        startingTech: ["dark_energy_tap", "scanlink_drone_network"],
        startingUnits: {
            destroyer: 2,
            dreadnought: 2,
            fighter: 2,
            infantry: 2,
            mech: 1,
            spacedock: 1,
        },
        techs: [],
        units: ["maximus", "aegis", "aegis_2", "repairitor"],
    },
    {
        abilities: ["projection_of_power", "industrialists"],
        commodities: 4,
        faction: "celdauri",
        home: 3219,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["henry_storcher"],
            heroes: ["titus_flavius"],
        },
        promissoryNotes: ["trade_alliance"],
        source: "discordant_stars",
        startingTech: [
            "antimass_deflectors",
            "sarween_tools",
            "plasma_scoring",
        ],
        startingUnits: {
            carrier: 2,
            destroyer: 1,
            fighter: 4,
            infantry: 3,
            pds: 1,
            spacedock: 1,
        },
        techs: [],
        units: ["supremacy", "trade_port", "trade_port_2", "minuteman"],
    },
    {
        abilities: ["celestial_guides", "singularity_point", "voidsailors"],
        commodities: 3,
        faction: "nivyn",
        home: 3220,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["thussad_krath"],
            heroes: ["krill_drakkon"],
        },
        promissoryNotes: ["nivyn_guidance"],
        source: "discordant_stars",
        startingTech: ["dark_energy_tap", "plasma_scoring"],
        startingUnits: {
            carrier: 1,
            cruiser: 1,
            dreadnought: 1,
            fighter: 3,
            infantry: 3,
            mech: 1,
            spacedock: 1,
        },
        techs: [],
        units: ["eradica", "voidflare_warden", "voidflare_warden_2"],
    },
    {
        abilities: ["priviledged_citizenry", "combat_drones"],
        commodities: 3,
        faction: "mirveda",
        home: 3221,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["assault_machina"],
            heroes: ["wrath_machina"],
        },
        promissoryNotes: ["rapid_excavation"],
        source: "discordant_stars",
        startingTech: ["ai_development_algorithm"],
        startingUnits: {
            carrier: 2,
            cruiser: 1,
            fighter: 5,
            infantry: 2,
            pds: 1,
            spacedock: 1,
        },
        techs: [],
        units: ["nexus", "gauss_cannon", "gauss_cannon_2", "javelin"],
    },
    {
        abilities: ["zealous", "ruthless"],
        commodities: 3,
        faction: "kortali",
        home: 3222,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["queen_lorena"],
            heroes: ["queen_nadalia"],
        },
        promissoryNotes: ["blessing_of_the_queens"],
        source: "discordant_stars",
        startingTech: ["psychoarchaeology", "plasma_scoring"],
        startingUnits: {
            carrier: 2,
            cruiser: 1,
            fighter: 2,
            infantry: 4,
            pds: 1,
            spacedock: 1,
        },
        techs: [],
        units: ["magistrate", "justicar"],
    },
    {
        abilities: ["cloaked_fleet", "shroud_of_lith", "treasure_hunters"],
        commodities: 3,
        faction: "kollecc",
        home: 3223,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["kado_smahqar"],
            heroes: ["dorrahn_griphyn"],
        },
        promissoryNotes: ["ai_survey"],
        source: "discordant_stars",
        startingTech: ["scanlink_drone_network"],
        startingUnits: {
            carrier: 2,
            cruiser: 1,
            fighter: 2,
            infantry: 4,
            spacedock: 1,
        },
        techs: [],
        units: ["nightingale_v", "nightshade_vanguard"],
    },
    {
        abilities: ["conspirators", "ancient_knowledge"],
        commodities: 3,
        faction: "rhodun",
        home: 3224,
        leaders: {
            agents: ["UNKNOWN_XXX"],
            commanders: ["bishop_ulin"],
            heroes: ["saint_binal"],
        },
        promissoryNotes: ["favor_of_rhodun"],
        source: "discordant_stars",
        startingTech: ["biostims"],
        startingUnits: {
            carrier: 1,
            cruiser: 1,
            destroyer: 1,
            fighter: 3,
            infantry: 4,
            spacedock: 1,
        },
        techs: [],
        units: ["reckoning", "templar"],
    },
];
