module.exports = {
    desks: [
        // East
        {
            colorName: "pink",
            hexColor: "#FF84D6",
            plasticHexColor: "#F46FCD",
            pos: { x: 0, y: 160 },
            yaw: 180.0,
            defaultPlayerSlot: 5,
            playerCounts: [7, 8],
        },
        // North (right to left)
        {
            colorName: "green",
            hexColor: "#5AE35A",
            plasticHexColor: "#00A306",
            pos: { x: 102.4, y: 100.8 },
            yaw: 120,
            defaultPlayerSlot: 1,
            playerCounts: [3, 4, 5, 6, 7, 8],
        },
        {
            colorName: "red",
            hexColor: "#FF2417",
            plasticHexColor: "#CB0000",
            pos: { x: 129.4, y: 0 },
            yaw: 90.0,
            defaultPlayerSlot: 16,
            playerCounts: [2, 5, 6, 7, 8],
        },
        {
            colorName: "yellow",
            hexColor: "#FFDA00",
            plasticHexColor: "#FFDA00",
            pos: { x: 102.4, y: -100.8 },
            yaw: 60,
            defaultPlayerSlot: 9,
            playerCounts: [3, 4, 5, 6, 7, 8],
        },
        // West
        {
            colorName: "orange",
            hexColor: "#FF932B",
            plasticHexColor: "#FF7603",
            pos: { x: 0, y: -160 },
            yaw: 0,
            defaultPlayerSlot: 6,
            playerCounts: [8],
        },
        // South (left to right)
        {
            colorName: "purple",
            hexColor: "#C800FF",
            plasticHexColor: "#5E219C",
            pos: { x: -102.4, y: -100.8 },
            yaw: -60,
            defaultPlayerSlot: 4,
            playerCounts: [4, 5, 6, 7, 8],
        },
        {
            colorName: "blue",
            hexColor: "#07B2FF",
            plasticHexColor: "#07B2FF",
            pos: { x: -129.4, y: 0 },
            yaw: -90.0,
            defaultPlayerSlot: 15,
            playerCounts: [1, 2, 3, 6, 7, 8],
        },
        {
            colorName: "white",
            hexColor: "#BABABA",
            plasticHexColor: "#C1C1C1",
            pos: { x: -102.4, y: 100.8 },
            yaw: -120,
            defaultPlayerSlot: 18,
            playerCounts: [4, 5, 6, 7, 8],
        },
    ],
};
